### ISSUE TITLE
mac 0.1.0 (0.1.0) 下载速度为0

### ISSUE THREAD

**Issue by dukoalad** [j-wyatt-a/N_m3u8DL-RE-GUI#2]
1. Mac版本 版本0.1.0 (0.1.0) 下载速度为0 ，m3u8 

https://pl-ali.youku.com/playlist/m3u8?vid=XNDkwMzAxMzQ2MA%3D%3D&type=cmaf4hd3&ups_client_netip=6f1ee620&utid=oD1%2FGxUern0CAW8h4YJBBKVr&ccode=0502&psid=b7532d4791b626a7e5f18f3739cad3e541346&ups_userid=21513341&ups_ytid=351698242&app_ver=9.1.84&duration=2000&expire=18000&drm_type=19&drm_device=7&drm_default=16&sm=1&nt=1&oss_file=05007E00006081AD018BB780000000C610416D-FA03-4E2F-8EAD-946E326FFACE&media_type=standard%2Csubtitle&dyt=0&ups_ts=1668573131&onOff=16&encr=0&ups_key=0e08b9c2fe1ac2ba1a5598bc20b22d91&ckt=5&m_onoff=0

2.以后网页地址必须输入吗？

**Comment by j2wyatt** [comment]
1. 这个链接请求应该是被对方的服务器拒绝了

3. 是的，网页地址是必填项
